name: 'Backlog Notifier'
description: 'Automatically comments on tickets connected to your PRs, with the release version, when they get released.'
inputs:
  repo-references:
    description: 'Unique, human readable (1) identifiers and (2) repository names in JSON format. (1) are used as prefixes for issue numbers in PR description bodies. (2) The names of the linked repositories. Both are specified as list of associated arrays. You can specify as many ID/repo combinations as you want. The identifiers should be single words, like BACKLOG or BUGLOG which e.g. could identify repos for backlog and bug tickets. The ID, as the action searches it in the PR description, should be the prefix of the issue number. Prefix and the issue number must be separated by a dash, e.g. `BACKLOG-539`.'
    required: true
    default: |
      {
        "data": [
          {"repo_id": "BACKLOG", "repo_name": "backlog"}
        ]
      }
  message:
    description: 'The message that is posted in the backlog ticket. Use `#` as placeholder for the version number.'
    required: true
    default: 'Dang! This feature has just been released in version # 🎉'
  changelog-path:
    description: 'The path to the CHANGELOG.md file. Defaults to CHANGELOG.md'
    required: false
    default: 'CHANGELOG.md'
branding:
  icon: 'bell'  
  color: 'green'
runs:
  using: 'node20'
  main: './dist/index.js'